package com.employee.management.service;

import com.employee.management.entity.Employee;
import com.employee.management.entity.Task;
import com.employee.management.repository.EmployeeRepository;
import com.employee.management.repository.TaskRepository;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.awt.Color;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class PdfReportService {

    private final TaskRepository taskRepository;
    private final EmployeeRepository employeeRepository;

    public PdfReportService(TaskRepository taskRepository, EmployeeRepository employeeRepository) {
        this.taskRepository = taskRepository;
        this.employeeRepository = employeeRepository;
    }

    @Transactional(readOnly = true)
    public ByteArrayInputStream generateAllTasksReport() {
        Document document = new Document(PageSize.A4, 36, 36, 36, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Fonts
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, new Color(79, 70, 229));
            Font subtitleFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.GRAY);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE);
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Color.BLACK);

            // Title
            Paragraph title = new Paragraph("Employee Task Status Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph subtitle = new Paragraph("Generated by Employee Management & Task Tracking System", subtitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(20);
            document.add(subtitle);

            // Table
            PdfPTable table = new PdfPTable(6);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{1.5f, 3.5f, 2.0f, 1.5f, 1.5f, 2.0f});

            String[] headers = {"ID", "Title", "Assigned To", "Priority", "Status", "Due Date"};
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
                cell.setBackgroundColor(new Color(79, 70, 229));
                cell.setPadding(6);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
            }

            List<Task> tasks = taskRepository.findAll();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            for (Task task : tasks) {
                table.addCell(new PdfPCell(new Phrase("#" + task.getId(), cellFont)));
                table.addCell(new PdfPCell(new Phrase(task.getTitle(), cellFont)));

                String assignee = task.getAssignedEmployee() != null ?
                        task.getAssignedEmployee().getFirstName() + " " + task.getAssignedEmployee().getLastName() : "Unassigned";
                table.addCell(new PdfPCell(new Phrase(assignee, cellFont)));

                table.addCell(new PdfPCell(new Phrase(task.getPriority().name(), cellFont)));
                table.addCell(new PdfPCell(new Phrase(task.getStatus().name(), cellFont)));
                table.addCell(new PdfPCell(new Phrase(task.getDueDate() != null ? task.getDueDate().format(formatter) : "N/A", cellFont)));
            }

            document.add(table);
            document.close();

        } catch (Exception e) {
            System.err.println("Failed to generate PDF report: " + e.getMessage());
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    @Transactional(readOnly = true)
    public ByteArrayInputStream generateEmployeeSummaryReport(Long employeeId) {
        Employee employee = employeeRepository.findById(employeeId)
                .orElseThrow(() -> new RuntimeException("Employee not found"));

        Document document = new Document(PageSize.A4, 36, 36, 36, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, new Color(79, 70, 229));
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE);
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Color.BLACK);

            Paragraph title = new Paragraph("Employee Performance Summary Sheet", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(15);
            document.add(title);

            // Employee Info Block
            PdfPTable infoTable = new PdfPTable(2);
            infoTable.setWidthPercentage(100);
            infoTable.setSpacingAfter(20);

            infoTable.addCell(new PdfPCell(new Phrase("Employee Name: " + employee.getFirstName() + " " + employee.getLastName(), cellFont)));
            infoTable.addCell(new PdfPCell(new Phrase("Department: " + employee.getDepartment(), cellFont)));
            infoTable.addCell(new PdfPCell(new Phrase("Email: " + employee.getEmail(), cellFont)));
            infoTable.addCell(new PdfPCell(new Phrase("Designation: " + employee.getDesignation(), cellFont)));
            document.add(infoTable);

            // Task List
            List<Task> tasks = taskRepository.findByAssignedEmployeeId(employeeId);

            Paragraph taskHeading = new Paragraph("Assigned Tasks (" + tasks.size() + ")", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14));
            taskHeading.setSpacingAfter(10);
            document.add(taskHeading);

            PdfPTable table = new PdfPTable(5);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{1.0f, 4.0f, 2.0f, 2.0f, 2.0f});

            String[] headers = {"ID", "Task Title", "Priority", "Status", "Due Date"};
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
                cell.setBackgroundColor(new Color(79, 70, 229));
                cell.setPadding(6);
                table.addCell(cell);
            }

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            for (Task task : tasks) {
                table.addCell(new PdfPCell(new Phrase("#" + task.getId(), cellFont)));
                table.addCell(new PdfPCell(new Phrase(task.getTitle(), cellFont)));
                table.addCell(new PdfPCell(new Phrase(task.getPriority().name(), cellFont)));
                table.addCell(new PdfPCell(new Phrase(task.getStatus().name(), cellFont)));
                table.addCell(new PdfPCell(new Phrase(task.getDueDate() != null ? task.getDueDate().format(formatter) : "N/A", cellFont)));
            }

            document.add(table);
            document.close();

        } catch (Exception e) {
            System.err.println("Failed to generate employee PDF report: " + e.getMessage());
        }

        return new ByteArrayInputStream(out.toByteArray());
    }
}
